apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ml-app
  labels:
    app: fastapi-ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-ml-app
  template:
    metadata:
      labels:
        app: fastapi-ml-app
    spec:
      containers:
      - name: fastapi-ml-container
        image: ghcr.io/frallmeister/ml-fastapi-argo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
