apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi-ml-app
  ports:
    - port: 80        # Service port (internal cluster port)
      targetPort: 80  # Container port to forward to (from Deployment)
      nodePort: 30008 # NodePort on the host (30000-32767 range; optional specification)
